version: '3.8'

services:
  bitwarden-agent:
    build:
      context: ./bitwarden-agent
    env_file:
      - .env
    volumes:
      - env_vars:/run/secrets
    networks:
      - spark-network
    command: ["/bin/sh", "-c", "/entrypoint.sh && sleep 5"]
    depends_on:
      - spark-master

  spark-master:
    image: bitnami/spark:3.5.0
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"
    networks:
      - spark-network

  spark-worker-1:
    image: bitnami/spark:3.5.0
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: "2"
      SPARK_WORKER_MEMORY: "2g"
      SPARK_MASTER_URL: spark://spark-master:7077
    networks:
      - spark-network

  spark-worker-2:
    image: bitnami/spark:3.5.0
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: "2"
      SPARK_WORKER_MEMORY: "2g"
      SPARK_MASTER_URL: spark://spark-master:7077
    networks:
      - spark-network

  mysql:
    image: mysql:8
    env_file:
      - /run/secrets/env_secrets.env
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "crypto_bot"
    ports:
      - "3306:3306"
    networks:
      - spark-network
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
      - env_vars:/run/secrets
    depends_on:
      - bitwarden-agent

  jupyter:
    build: ./jupyter
    image: custom-jupyter:latest
    platform: linux/amd64
    ports:
      - "8888:8888"
    volumes:
      - env_vars:/run/secrets
      - ./:/home/jovyan/work/crypto-bot
    env_file:
      - /run/secrets/env_secrets.env
    environment:
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      COIN_API_KEY: "${COIN_API_KEY}"
      SPARK_MASTER: "spark://spark-master:7077"
      PYSPARK_PYTHON: python3
      PYSPARK_DRIVER_PYTHON: python3
      SPARK_LOCAL_IP: jupyter
    command: start-notebook.sh --NotebookApp.base_url='/jupyter/' --NotebookApp.token='' --NotebookApp.allow_origin='*'
    depends_on:
      - bitwarden-agent
      - spark-master
      - spark-worker-1
      - spark-worker-2
      - mysql

  dash-app:
    build:
      context: ./dashApp
    ports:
      - "8050:8050"
    volumes:
      - env_vars:/run/secrets
      - ./dashApp:/app
    env_file:
      - /run/secrets/env_secrets.env
    environment:
      COIN_API_KEY: "${COIN_API_KEY}"
    networks:
      - spark-network
    depends_on:
      - bitwarden-agent
      - mysql

networks:
  spark-network:

volumes:
  mysql_data:
  env_vars:
